apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-replica-set
  labels:
    app: busybox
spec:
  template:
    metadata:
      name: busybox-pod
      labels:
        app: busybox
        label: busybox-pod
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  replicas: 2
  selector:
    matchLabels:
      app: busybox

#kubectl replace -f rs-definition.yaml: Replace the existing replica set with the new replica set definition
#kubectl scale --replicas=6 -f rs-definition.yaml: Scale the replica set to 6 replicas but the replica set definition file should have replicas set to 2