apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-controller
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-webserver
        label: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 1