apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
    label: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']